# Generated by Django 4.2.4 on 2023-08-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=11)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
