# Generated by Django 4.2.4 on 2023-09-01 04:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('course_fee', models.IntegerField()),
                ('syllabus', ckeditor.fields.RichTextField(default='syllabus')),
                ('about_course', ckeditor.fields.RichTextField(default='about_course')),
                ('stars', models.IntegerField(default=3)),
            ],
        ),
    ]
