# Generated by Django 4.2.4 on 2023-09-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0003_courses_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_designation', models.CharField(max_length=100)),
                ('trainer_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startupapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('college_name', models.CharField(max_length=120)),
                ('address', models.TextField(max_length=200)),
                ('street', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('pincode', models.IntegerField()),
                ('computer_knowledge', models.CharField(max_length=50)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='startupapp.trainer')),
            ],
        ),
    ]
