# Generated by Django 4.2.4 on 2023-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0004_trainer_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='course',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
