# Generated by Django 4.2.4 on 2023-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0006_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=50)),
                ('logintime', models.CharField(max_length=50)),
                ('logouttime', models.CharField(max_length=50)),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
